# Generated by Django 5.2.4 on 2026-03-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название проекта')),
                ('description', models.TextField(blank=True, verbose_name='описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('github_url', models.URLField(blank=True, verbose_name='ссылка на Github')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6, verbose_name='статус')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='автор проекта')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_projects', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
